spring:
  application:
    name: FirstServer
  datasource:
    url: jdbc:mariadb://localhost/memo
#     >>이 위치로 DB를 찾아가서 데이터 전달 localhost= 나자신
    username: root
    password: green502


mybatis:
  mapper-locations: mappers/**/*.xml